name: Jekyll AWS CloudFront Deployment

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Start Jekyll Build
      run: |
        bundle install
        bundle list
        bundle exec jekyll clean
        bundle exec jekyll build
